#pragma once
#include <windows.h>
#include <tlhelp32.h>
#include <iostream>
#include <thread>
#include <string>
#include "Entity.h"
#include "LocalPlayer.h"
#include "NullMemory.h"
#include "Xor.h"
#include "lolz.hpp"
#include "Math.h"
#include "W2S.h"
#include <corecrt_math_defines.h>"